version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zXcVbN123!
      MONGO_INITDB_DATABASE: pnf_simulator
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: zXcVbN123!

  pnf-simulator:
    image: onap/org.onap.integration.nfsimulator.vesclient
    ports:
      - "5000:5000"
    environment:
      USE_CERTIFICATE_FOR_AUTHORIZATION: "true"
    volumes:
      - ./logs:/var/log
      - ./templates:/app/templates
      - ./store:/app/store
      - ./src/main/resources/application.properties:/app/application.properties
    restart: on-failure
    depends_on:
      - mongo
      - mongo-express
